name: Evaluate Repository

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run evaluation script
        run: python evaluate_repo.py

      - name: Append progress report to README
        run: |
          cat progress_report.md >> README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m 'Update README with progress report'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}